Repository symphonycms/symphony-2, pull requests merged in 2018-03, with the labels that each got.

#2802 Properly set and pass the new author's id
  symphony/content/content.systemauthors.php
  symphony/lib/toolkit/class.author.php
Labels: 1 - Minor

#2810 Ignore errors generated by unlink for delete methods
  symphony/lib/toolkit/class.general.php
Labels: 1 - Minor

#2617 Add the Content-ID header on attachments
  symphony/lib/toolkit/class.emailgateway.php
Labels: 1 - Minor, Needs Testing, WIP (do not merge!)

#2813 Add missing Resources delegates
  symphony/content/content.blueprintsdatasources.php
  symphony/content/content.blueprintsevents.php
  symphony/lib/toolkit/class.resourcespage.php
Labels: 1 - Minor, Datasource Editor
