Repository symphonycms/symphony-2, pull requests merged in 2018-02, with the labels that each got.

#2801 Make the default max log size to 10Mb
  install/includes/config_default.php
Labels: 1 - Minor, WIP (do not merge!)

#2798 JSON to XML: Only add element attributes if useful
  symphony/lib/toolkit/class.json.php
Labels: 1 - Minor, Enhancement

#2796 Make SMTP class reset on unexpected responses
  symphony/lib/toolkit/class.smtp.php
Labels: 1 - Minor, Core Email API

#2793 Fix profiler samples
  symphony/lib/toolkit/class.frontendpage.php
  symphony/lib/toolkit/class.profiler.php
Labels: 2 - Nominal, Enhancement

#2799 Add ― to transliterations
  symphony/lib/lang/transliterations.php
Labels: 1 - Minor, WIP (do not merge!)

#2808 Add a default security.txt file
  .well-known/security.txt
Labels: 1 - Minor

#2805 Make DS params in XML optional
  symphony/content/content.blueprintsdatasources.php
  symphony/lib/toolkit/class.frontendpage.php
Labels: 3 - Major, Controversial, WIP (do not merge!)

#2597 Better error handling and disabled display of exception data by default for 3.0.0
  symphony/lib/boot/bundle.php
  symphony/lib/core/class.errorhandler.php
  symphony/lib/core/class.frontend.php
  symphony/lib/core/class.symphony.php
  symphony/template/fatalerror.disabled.tpl
Labels: 3 - Major, Needs Testing

#2806 Data Sources: Allow to output system IDs only
  symphony/content/content.blueprintsdatasources.php
Labels: 1 - Minor
