Repository symphonycms/symphony-2, pull requests merged in 2018-04, with the labels that each got.

#2815 Fix the privilege escalation bug
  symphony/content/content.systemauthors.php
Labels: 4 - Critical, WIP (do not merge!)

#2804 Remove parameters as arguments
  symphony/lib/toolkit/class.frontendpage.php
  symphony/lib/toolkit/class.general.php
  symphony/lib/toolkit/class.xsltpage.php
  symphony/lib/toolkit/class.xsltprocess.php
Labels: 1 - Minor, Controversial, WIP (do not merge!)

#2821 Prevent empty session creation
  symphony/lib/core/class.session.php
Labels: 1 - Minor

#2822 Double encode value in displayPublishPanel()
  symphony/lib/toolkit/class.general.php
  symphony/lib/toolkit/fields/field.textarea.php
Labels: 1 - Minor
