Repository symphonycms/symphony-2, pull requests merged in 2018-05, with the labels that each got.

#2831 Use semver for version comparison
  composer.json
  composer.lock
  install/lib/class.installer.php
  install/lib/class.updater.php
  symphony/lib/core/class.log.php
  symphony/lib/core/class.symphony.php
  symphony/lib/toolkit/class.extension.php
  symphony/lib/toolkit/class.extensionmanager.php
Labels: 1 - Minor, WIP (do not merge!)

#2839 Remove unset $id (introduced by copy/paste)
  symphony/content/content.blueprintsdatasources.php
Labels: 1 - Minor

#2840 Fix broken sessions with PHP 7.0.*
  symphony/lib/core/class.session.php
Labels: 2 - Nominal, PHP 7
