Repository symphonycms/symphony-2, pull requests merged in 2019-02, with the labels that each got.

#2876 Suppress opcache warnings when opcache_invalidate does not work
  symphony/content/content.blueprintsdatasources.php
  symphony/content/content.blueprintsevents.php
  symphony/content/content.systempreferences.php
Labels: 1 - Minor

#2871 Fix PHP 7 warnings
  symphony/content/content.blueprintsdatasources.php
  symphony/content/content.blueprintsevents.php
  symphony/content/content.systemauthors.php
Labels: 1 - Minor, PHP 7

#2874 $provides array in Extension class should be protected, not private.
  symphony/lib/toolkit/class.extension.php
Labels: 1 - Minor, Fix found
